import { test, expect } from "playwright/test";

import { safeResumePdfFilename } from "../../domain/resume-documents/pdfSnapshot";
import { resumePdfFixture } from "../fixtures/resumePdfFixture";

const pdfBytes = Buffer.from("%PDF-1.4\n% deterministic browser Blob fixture\n", "ascii");
const pageCount = 6;

test("generated bytes back one shared iframe/download Blob URL with deterministic cleanup", async ({ page }) => {
  const filename = safeResumePdfFilename(resumePdfFixture.documentName);
  await page.route("https://resume.test/api/resume/documents/pdf", async (route) => {
    await route.fulfill({
      status: 200,
      body: pdfBytes,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="resume.pdf"; filename*=UTF-8''${encodeURIComponent(filename)}`,
        "X-Resume-Pdf-Page-Count": String(pageCount),
      },
    });
  });
  await page.route("https://resume.test/", async (route) => route.fulfill({ status: 200, contentType: "text/html", body: "<!doctype html><title>Resume PDF fixture</title>" }));
  await page.goto("https://resume.test", { waitUntil: "domcontentloaded" });
  await page.setContent(`
    <main>
      <p id="status">PDF 미리보기를 만드는 중입니다.</p>
      <div id="preview"></div>
      <button id="close" type="button">닫기</button>
    </main>
    <script>
      window.revokedResumeUrls = [];
      const originalRevoke = URL.revokeObjectURL.bind(URL);
      URL.revokeObjectURL = (url) => { window.revokedResumeUrls.push(url); originalRevoke(url); };
      let resourceUrl = null;
      fetch("https://resume.test/api/resume/documents/pdf", { method: "POST" }).then(async (response) => {
        const blob = await response.blob();
        resourceUrl = URL.createObjectURL(blob);
        const iframe = document.createElement("iframe");
        iframe.title = "생성된 이력서 PDF 미리보기";
        iframe.src = resourceUrl;
        const download = document.createElement("a");
        download.textContent = "PDF 다운로드";
        download.href = resourceUrl;
        download.download = ${JSON.stringify(filename)};
        document.querySelector("#preview").append(iframe, download);
        document.querySelector("#status").textContent = "PDF 생성 완료 · 정확히 " + response.headers.get("X-Resume-Pdf-Page-Count") + "페이지";
      });
      document.querySelector("#close").addEventListener("click", () => {
        if (resourceUrl) URL.revokeObjectURL(resourceUrl);
        document.querySelector("#preview").replaceChildren();
      });
    </script>
  `);

  await expect(page.getByText(`PDF 생성 완료 · 정확히 ${pageCount}페이지`)).toBeVisible();
  const iframe = page.getByTitle("생성된 이력서 PDF 미리보기");
  const download = page.getByRole("link", { name: "PDF 다운로드" });
  await expect(iframe).toBeVisible();
  await expect(download).toHaveAttribute("download", filename);
  const iframeUrl = await iframe.getAttribute("src");
  const downloadUrl = await download.getAttribute("href");
  expect(iframeUrl).toBeTruthy();
  expect(downloadUrl).toBe(iframeUrl);
  await page.waitForTimeout(100);
  await expect(iframe).toHaveCount(1);

  await page.getByRole("button", { name: "닫기" }).click();
  await expect(iframe).toHaveCount(0);
  expect(await page.evaluate(() => (window as unknown as { revokedResumeUrls: string[] }).revokedResumeUrls)).toEqual([iframeUrl]);
});
