import { recommendationCopy } from "../../domain/press-workflow/evaluation/analysis";
import type { buildReport } from "../../domain/press-workflow/evaluation/report";

const esc = (s: unknown) => String(s ?? "—").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
const names: Record<string, string> = { FACTUAL_SUPPORT: "사실 근거", REQUIRED_FACTS: "필수 정보", STYLE_LEAKAGE: "예시 오염", PROMOTIONAL_CLAIMS: "근거 없는 과장", REQUESTED_STYLE: "요청 문체" };
const pct = (v: number) => `${(v * 100).toFixed(1)}%`;
export function insightsHtml(report: ReturnType<typeof buildReport>) {
  const insight = report.insights;
  return `<section id="quality-insights"><h2>품질 분석과 개선 제안</h2><p>자동 평가의 관측 결과와 사람의 확인을 함께 분석합니다. 제안은 검증할 가설이며 효과가 입증된 수정은 아닙니다.</p>
    <div class="grid"><article><h3>평가기와 사람의 비교</h3><p class="score">${report.review.agreements} / ${report.review.comparableCount}</p><p>비교 가능한 선택 중 일치 · 전체 검토 ${report.review.labelledCount}/${report.review.eligibleCount}</p><p>사람이 지적한 결함 탐지 ${report.review.detectedDefectCount}/${report.review.defectCount}</p><small>검토한 표본의 진단입니다. 우선 검토한 사례의 비율을 전체 정확도로 해석하지 않습니다.</small></article>
    <article><h3>변경 전후 차이의 불확실성</h3>${insight.paired.filter(p => p.groupCount > 0).map(p => `<p><strong>${p.partition === "DEVELOPMENT" ? "개발 사례" : "별도 평가 사례"}</strong> · 독립 원문 ${p.completeGroups}/${p.groupCount}개 · 비교 ${p.pairCount}쌍</p><p>Ragas 평균 차이 ${p.meanDelta === null ? "—" : p.meanDelta.toFixed(3)}</p><p>${p.interval ? `탐색적 95% 구간 ${p.interval.low.toFixed(3)} ~ ${p.interval.high.toFixed(3)}` : p.state === "DEGENERATE" ? "차이가 모두 같아 구간 추정 보류" : "원문 10개 미만으로 구간 추정 보류"}</p><small>같은 원문의 반복은 묶어서 계산합니다. 제외된 원문 ${p.excludedGroups}개.</small>`).join("") || "<p>비교할 초안이 없습니다.</p>"}</article></div>
    <h3>우선 검토할 개선안</h3>${insight.recommendations.map((r, i) => { const copy = recommendationCopy[r.code]; return `<article><p class="eyebrow">제안 ${i + 1} · ${r.confidence === "HUMAN_CONFIRMED" ? "사람이 확인한 문제" : r.confidence === "AUTOMATIC_FLAG" ? "자동 판정 · 사람 확인 전" : "측정 진단"}</p><h3>${esc(copy.title)}</h3><p><strong>관측 근거:</strong> ${r.count}${r.code === "COLLECT_INDEPENDENT_CASES" ? "개 원문" : "개 초안"} ${esc(r.caseKeys.join(", "))}</p><p><strong>개선 제안:</strong> ${esc(copy.action)}</p><p><strong>효과 확인 방법:</strong> ${esc(copy.validation)}</p>${r.caseKeys.length ? '<small>대상 초안과 판정 이유는 아래 원본 평가 및 사람 검토 내역에서 확인할 수 있습니다.</small>' : ""}</article>`; }).join("")}
    <details><summary>오류 유형별 빈도와 95% 구간</summary><p>각 원문에서 반복 실행 중 한 번이라도 위반이면 해당 원문의 위반으로 셉니다. 모든 반복을 판정할 수 있는 원문만 분모에 들어갑니다. 판단 불가는 별도로 표시합니다. 합성 입력의 조건부 통계이며, 고객 전체의 품질 구간이 아닙니다.</p><div style="overflow-x:auto"><table><thead><tr><th>분할 / 설정</th><th>항목</th><th>위반 원문 / 평가 원문</th><th>95% 구간</th><th>판단 불가 원문</th></tr></thead><tbody>${insight.rates.filter(r => r.groupCount > 0).map(r => `<tr><td>${r.partition} / ${r.variant}</td><th>${esc(names[r.criterion])}</th><td>${r.affectedGroups}/${r.evaluatedGroups}</td><td>${r.interval ? `${pct(r.interval.low)} ~ ${pct(r.interval.high)}` : "—"}</td><td>${r.unknownGroups}</td></tr>`).join("")}</tbody></table></div><p>Wilson 구간 · 쌍별 원문 bootstrap 4,000회 · 제안 자동 적용 없음</p></details></section>`;
}
