import type { ReviewSession } from "../../domain/press-workflow/evaluation/quick-review";
const esc = (s: unknown) => String(s ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
const hints: Record<string, string> = { FACTUAL_SUPPORT: "모든 사실 주장을 제공된 근거로 확인할 수 있나요?", REQUIRED_FACTS: "필수 정보가 빠짐없이 정확하게 들어 있나요?", STYLE_LEAKAGE: "표현 예시의 이름·수치·성과를 가져오지 않았나요?", PROMOTIONAL_CLAIMS: "근거 없는 성능·우수성·시장 평가가 없나요?", REQUESTED_STYLE: "요청한 문체로 작성되었나요?" };
export function quickReviewHtml(session: ReviewSession, token: string) {
  const completed = session.queue.filter(q => session.packet.entries.find(e => e.reviewId === q.reviewId)!.labels.every(l => l.judgment !== null)).length;
  const boot = JSON.stringify({ token, sessionId: session.sessionId, revision: session.revision }).replaceAll("<", "\\u003c");
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>선택으로 검토 · PressTuner</title><style>
    :root{font:16px/1.6 system-ui;color:#183c36;background:#f4f7f5}body{margin:0}main{max-width:1080px;margin:auto;padding:32px 20px}h1{font-size:32px;letter-spacing:-.04em}h2{font-size:22px}h3{font-size:17px}article{background:#fff;border:1px solid #d4dfd9;border-radius:14px;padding:24px;margin:24px 0}.grid{display:grid;grid-template-columns:1fr 1.15fr;gap:24px}pre{font:inherit;white-space:pre-wrap;overflow-wrap:anywhere;margin:0}li{margin:8px 0}fieldset{border:0;border-top:1px solid #d4dfd9;margin:16px 0;padding:18px 0}legend{padding-top:16px;font-weight:600}button{font:inherit;padding:10px 16px;border-radius:8px;background:#fff;border:1px solid #a3b9af;cursor:pointer;margin:5px 5px 0 0}button[aria-pressed=true]{background:#185a4b;color:#fff}button:disabled{opacity:.5}.sticky{position:sticky;top:0;background:#e9f2ed;padding:12px;border:1px solid #b9cdc2;border-radius:8px;z-index:2}a{color:#176b54}.tag{font-size:13px;color:#587367}details{margin:16px 0}#status{margin:0}small{color:#526d63}@media(max-width:700px){.grid{grid-template-columns:1fr}main{padding:20px 12px}article{padding:16px}h1{font-size:27px}}</style></head><body><main>
    <p class="tag">PRESSTUNER · 선택형 사람 검토</p><h1>읽고 선택하면 저장됩니다</h1><p>이유를 쓰거나 파일을 저장할 필요가 없습니다. 직접 확인한 항목만 선택하세요. 버튼 선택은 본인이 읽고 판정했다는 확인으로 기록됩니다. 판단이 어렵거나 건너뛰어도 괜찮습니다.</p>
    <div class="sticky"><p id="status" role="status">${session.queue.length ? `검토 완료 ${completed}/${session.queue.length}개 초안 · 저장 버전 ${session.revision}` : "이 자료는 이미 검토했습니다. 추가 선택 없이 분석 결과를 확인하세요."}</p><a href="/report">분석과 개선 제안 보기</a></div>
    <p>전체 ${session.packet.entries.length}개 중 이번 검토 ${session.queue.length}개 · 다음 검토 대기 ${session.remainingDrafts}개. 무작위 점검과 우선 검토를 구분해 기록하며 자동 판정과 설정 이름은 숨깁니다.</p>
    ${session.queue.map((q, i) => { const e = session.packet.entries.find(e => e.reviewId === q.reviewId)!; return `<article><p class="tag">검토 ${i + 1} · ${q.selection === "RANDOM_AUDIT" ? "무작위 점검" : "우선 검토"}</p><div class="grid"><div><h2>요청과 근거</h2><p>${esc(e.request)}</p><ul>${e.facts.map(f => `<li>${esc(f.content)}${e.requiredFactIds.includes(f.id) ? " <strong>필수</strong>" : ""}</li>`).join("")}</ul><p><strong>문체:</strong> ${esc(e.requestedStyle)}</p><details><summary>표현 참고 예시 · 사실 근거 아님</summary><p>${esc(e.styleExamples)}</p></details></div><div><h2>검토할 초안</h2><pre>${esc(e.draft)}</pre></div></div>${e.labels.map(l => `<fieldset data-entry="${e.reviewId}" data-criterion="${l.criterion}"><legend>${esc(hints[l.criterion])}</legend>${[["PASS", "충족"], ["FAIL", "위반"], ["UNCERTAIN", "판단 어려움"], ["", "건너뛰기"]].map(([v, t]) => `<button type="button" data-value="${v}" aria-pressed="${l.judgment !== null && l.judgment === v}">${t}</button>`).join("")}</fieldset>`).join("")}</article>`; }).join("")}
    <p><a href="/report">현재 분석과 개선 제안 확인</a></p><noscript>선택 저장에는 JavaScript가 필요합니다.</noscript></main><script>
    const state=${boot};let busy=false;document.querySelectorAll('button[data-value]').forEach(button=>button.addEventListener('click',async()=>{
      if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);const status=document.getElementById('status');status.textContent='선택을 저장하는 중…';const field=button.closest('fieldset');
      try{const response=await fetch('/selection',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':state.token},body:JSON.stringify({sessionId:state.sessionId,revision:state.revision,reviewId:field.dataset.entry,criterion:field.dataset.criterion,judgment:button.dataset.value||null,confirmed:true})});
        if(!response.ok)throw new Error(response.status===409?'다른 화면에서 변경됐습니다. 새로고침 후 다시 선택하세요.':'저장하지 못했습니다. 연결을 확인하고 같은 버튼을 다시 눌러 주세요.');const saved=await response.json();state.revision=saved.revision;field.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));status.textContent='저장됨 · '+saved.labelledCount+'개 항목 · 버전 '+saved.revision+' · 분석에 반영했습니다.'+(saved.summaryUpdated?'':' Console 요약 갱신은 실패했습니다. 서버를 재시작하면 복구됩니다.');
      }catch(error){status.textContent=error.message||'저장하지 못했습니다. 다시 선택해 주세요.';}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}
    }));</script></body></html>`;
}
