import type { PressAgentRagDebuggerRetrievalConfigurationId } from "@/domain/evaluation/pressAgentRagDebugger";
import type { PRESS_AI_SAMPLE_SCENARIOS } from "@/domain/press-ai-debugger/sampleManifest";
import type { PressAiKnowledgeDocument } from "@/lib/pressAiProcessDebuggerClient";
import { PressAiKnowledgeDocuments } from "./PressAiKnowledgeDocuments";
import { PressAiSampleScenarios } from "./PressAiSampleScenarios";

type Scenario = (typeof PRESS_AI_SAMPLE_SCENARIOS)[number];

export function PressAiRagSetup(props: { prompt: string; onPromptChange: (value: string) => void; retrieval: PressAgentRagDebuggerRetrievalConfigurationId; onRetrievalChange: (value: PressAgentRagDebuggerRetrievalConfigurationId) => void; scenarioId: string | null; onScenario: (scenario: Scenario) => void; onAddScenario: (scenario: Scenario) => void; adding: boolean; documents: PressAiKnowledgeDocument[]; selectedIds: string[]; onSelectedIdsChange: (ids: string[]) => void; onFiles: (files: File[]) => void; onRefresh: () => void; loading: boolean; progress: string; error: string | null; quota: any; disabled?: boolean }) {
  return <div className="mt-5 space-y-5"><PressAiSampleScenarios selectedId={props.scenarioId} onSelect={props.onScenario} onAdd={props.onAddScenario} adding={props.adding}/><div className="grid gap-5 lg:grid-cols-2"><PressAiKnowledgeDocuments documents={props.documents} selectedIds={props.selectedIds} onSelectedIdsChange={props.onSelectedIdsChange} onFiles={props.onFiles} onRefresh={props.onRefresh} loading={props.loading} progress={props.progress} error={props.error} disabled={props.disabled}/><fieldset disabled={props.disabled} className="rounded-xl border border-border p-4"><legend className="px-2 text-sm font-black">질의와 검색 구성</legend><label className="block text-sm font-bold" htmlFor="press-ai-rag-prompt">테스트 프롬프트</label><textarea id="press-ai-rag-prompt" value={props.prompt} onChange={(event) => props.onPromptChange(event.target.value)} rows={6} maxLength={12000} className="mt-2 w-full rounded-xl border border-border bg-background p-3"/><label className="mt-4 block text-sm font-bold" htmlFor="press-ai-retrieval">검색 프리셋</label><select id="press-ai-retrieval" value={props.retrieval} onChange={(event) => props.onRetrievalChange(event.target.value as PressAgentRagDebuggerRetrievalConfigurationId)} className="mt-2 min-h-11 w-full rounded-lg border border-border bg-background px-3"><option value="baseline-v1">기준선</option><option value="candidate-v3">역할 인식 후보</option></select>{props.quota ? <p className="mt-4 text-sm text-muted-foreground">문서 {props.quota.activeDocumentCount}/{props.quota.limits?.documents} · 최근 업로드 {props.quota.uploadsInWindow}/{props.quota.limits?.uploads}</p> : null}</fieldset></div></div>;
}
