import type { NarrativeBlockType } from "@/domain/resume-documents/model";

export const RESUME_DOCUMENT_LAYOUT = Object.freeze({
  baseFontSizePt: 9.5,
  baseLineHeight: 1.55,
  headerBottomGapMm: 8,
  headerBottomPaddingMm: 3,
  headerBorderWidthMm: 0.6,
  companyFontSizePt: 8.5,
  roleTopGapMm: 1,
  roleFontSizePt: 14,
  sectionGapMm: 7,
  sectionHeadingGapMm: 4,
  sectionHeadingBottomGapMm: 4,
  sectionHeadingBottomPaddingMm: 1.5,
  sectionHeadingBorderWidthMm: 0.3,
  sectionTitleFontSizePt: 13,
  durationFontSizePt: 8.5,
  emptyFontSizePt: 9,
  itemPeriodWidthMm: 26,
  itemColumnGapMm: 4,
  itemGapMm: 4,
  itemPeriodFontSizePt: 8.5,
  detailTypeFontSizePt: 7.5,
  itemTitleFontSizePt: 10.5,
  itemSubtitleFontSizePt: 8.5,
  itemBodyTopGapMm: 1,
  itemBodyFontSizePt: 9,
  itemBodyLineHeight: 1.65,
  groupLeftPaddingMm: 3,
  groupBorderWidthMm: 0.5,
  groupGapMm: 5,
  groupHeadingBottomGapMm: 3,
  groupTitleFontSizePt: 10.5,
  groupMetaFontSizePt: 8.5,
  tagGapMm: 2,
  tagVerticalPaddingMm: 1.5,
  tagHorizontalPaddingMm: 3,
  tagFontSizePt: 9.5,
  highlightColumns: 2,
  highlightGapMm: 3,
  highlightMinHeightMm: 27,
  highlightPaddingMm: 4,
  highlightBorderWidthMm: 0.35,
  highlightIndexFontSizePt: 7,
  highlightTitleFontSizePt: 11,
  highlightSubtitleFontSizePt: 8,
  highlightBodyFontSizePt: 8.5,
  highlightBodyLineHeight: 1.55,
  narrativeBlockGapMm: 2,
  narrativeBodyLineHeight: 1.7,
  narrativeHeadingLineHeight: 1.25,
});

export const RESUME_NARRATIVE_FONT_SIZES_PT: Readonly<Record<NarrativeBlockType, number>> = Object.freeze({
  p: 9.5,
  h1: 18,
  h2: 15.5,
  h3: 13.5,
  h4: 12,
  h5: 11,
  h6: 10,
});
