export const A4_WIDTH_MM = 210;
export const A4_HEIGHT_MM = 297;
export const RESUME_PAGE_MARGIN_TOP_MM = 16;
export const RESUME_PAGE_MARGIN_BOTTOM_MM = 16;
export const RESUME_PAGE_MARGIN_LEFT_MM = 18;
export const RESUME_PAGE_MARGIN_RIGHT_MM = 18;
export const RESUME_PRINTABLE_WIDTH_MM = A4_WIDTH_MM
  - RESUME_PAGE_MARGIN_LEFT_MM
  - RESUME_PAGE_MARGIN_RIGHT_MM;
export const RESUME_PRINTABLE_HEIGHT_MM = A4_HEIGHT_MM
  - RESUME_PAGE_MARGIN_TOP_MM
  - RESUME_PAGE_MARGIN_BOTTOM_MM;
